version: '3.9'
services:
    db:
        image: postgres
        container_name: chatbot-database
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'mysecretpassword'
    bot1:
        container_name: bot1
        build:
            context: .
        ports:
            - 8080:8080
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    bot2:
        container_name: bot2
        build:
            context: .
        ports:
            - 8081:8080
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    bot3:
          container_name: bot3
          build:
              context: .
          ports:
              - 8082:8080
          depends_on:
              - db
          environment:
              - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
              - SPRING_DATASOURCE_USERNAME=postgres
              - SPRING_DATASOURCE_PASSWORD=mysecretpassword
    lb:
        container_name: load-balancer
        build:
            context: ./nginx
        ports:
            - 80:80
        depends_on:
            - bot1
            - bot2
            - bot3